disabled_rules:
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - nesting
  - blanket_disable_command
  - void_function_in_ternary
line_length:
 warning: 200
 error: 300
file_length:
  warning: 650
  error: 1000
type_body_length:
  warning: 300
  error: 500

